Added most functionality back in, missing class in tomcat path:
Caused by: java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException

need to add json-simple.jar into tomcat's classpath